# Generated by Django 5.0.2 on 2024-02-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="num_of_donation",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
