# Generated by Django 5.0.2 on 2024-03-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("campaign_creator", "Campaign Creator"), ("donor", "Donor")],
                default="donor",
                null=True,
            ),
        ),
    ]
