# Generated by Django 5.0.2 on 2024-03-20 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_biography_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cin",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.RegexValidator(
                        message="cin number must be exactly 8 digits", regex="^\\d{8}$"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="telephone_number",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 8 digits.",
                        regex="^\\d{8}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
