# Generated by Django 5.0.2 on 2024-03-21 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_customuser_cin_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cin",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="cin number must be exactly 8 digits", regex="^\\d{8}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telephone_number",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 8 digits.",
                        regex="^\\d{8}$",
                    )
                ],
            ),
        ),
    ]
